### ISSUE TITLE
Support basic Livechat features

### ISSUE THREAD

**Issue by renatobecker** [RocketChat/Rocket.Chat.Apps-engine#122]
We need to extend the Apps/Engine, allowing to support basic Livechat features, such as:

Methods from **Livechat library**:
- Livechat.sendMessage(msgObj)
- Livechat.registerGuest(guestObj)
- Find Livechat Guests by a specific field(phone, id, token.. -> LivechatVisitors)
- Find (one) Livechat Room(s) by guest token(Rooms.findOpenByVisitorToken, findOpenByVisitorTokenAndDepartmentId);
- Livechat.transfer(room, guest, { roomId: rid, departmentId: department }))
- Livechat.closeRoom({ visitor, room, comment }));

Improve the interfaces, adding new specific Livechat fields:

**IRoom**:
- { v, ServedBy, closed, responseBy }

**IMessage**:
- { file, token, t }

In addition, we're facing an issue related to HTTP requests: We need to be able to pass the following props when sending an HTTP request:
- strictSSL
- rejectUnauthorized

**Comment by d-gubert** [comment]
We identified the need to access the `Upload` model through the engine, also

**Comment by renatobecker** [comment]
> We identified the need to access the `Upload` model through the engine, also

The same for `Departments`.. :P

**Comment by renatobecker** [comment]
We need to support this Livechat callback -> `livechat.closeRoom`.
