### ISSUE TITLE
Livechat features missing

### ISSUE THREAD

**Issue by renatobecker** [RocketChat/Rocket.Chat.Apps-engine#136]
To be able to complete the implementation of the new Caixa Sibot App(Bot integration for Caixa), we need to provide the resources described below:

- get access to field `departmentId` in `LivechatRooms`;
- Allow updating `customFields` in `Rooms`. Currently, this isn't possible because there are some validations on unsupported fields in Livechat rooms.

**Comment by d-gubert** [comment]
Solved by https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/140 and available currently in the `beta` version! :)
