### ISSUE TITLE
[Game Platform Foundation] Add unregisterComponent method for externalComponent

### ISSUE THREAD

**Issue by lolimay** [RocketChat/Rocket.Chat.Apps-engine#139]
Currently, the AppExternalComponentManager is missing `unregister` method. There exist the following problems:
- Disabled games are showing up in the Game Center
- Uninstalled apps are still in the "Game Center"

**Comment by d-gubert** [comment]
Usually this is handled by the Apps-Engine itself - take the slashcommands as example: you don't need to unregister the slashcommands when the app gets disabled/uninstalled, the engine handles the unregistering of such resources

**Comment by d-gubert** [comment]
Ah! I see. Yes, I thought you were suggesting to provide a method so that the _developer of the app could call the unregister method_ 😅

**Comment by d-gubert** [comment]
Closed as the functionality has made it into the alpha branch :)
