### ISSUE TITLE
Compiler Doesn't Complain on Invalid TypeScript References

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-engine#16]
Currently our internally compiler doesn't complain/error out whenever an Application contains invalid code and references. For example, we moved over to each handler being a promise so the return type is `Promise<T>` but if an old App is uploaded that only returns `T` it should fail but it doesn't.

**Comment by graywolf336** [comment]
A few more items to consider:

- When loading the engine, if the Rocket.Chat Apps ts-def package has been updated then we need to recompile all of the Apps and ensure they can compile and don't have any compile errors. If they do, then let's disable them and display that along with why.
- When installing/updating an application, the compiler errors are now returned so we need to display those errors in a nice friendly way. If the environment is in `development` and not `production`, then let's display the full errors in detail otherwise produce a log that can be sent and if their mail settings are configured we can even have the option to email the author of the App or when we get the marketplace, errors can be sent to the developer console/center.

**Comment by graywolf336** [comment]
This is now related to #7 :)

**Comment by graywolf336** [comment]
For some work done on this, see this commit: https://github.com/RocketChat/Rocket.Chat.Apps-engine/commit/db3c81901342c5135f57f7d4c800ea1bfa5c6688

**Comment by thassiov** [comment]
Closing this issue with two comments:
- this is an outdated issue
- since we have plans to remove the ts compiler from Rocket.Chat, we will, by default, solve the compilation problem. Compilation becomes the responsibility of another software.
