### ISSUE TITLE
Cannot get topic from room retrieved using read.getRoomReader().getById(...)

### ISSUE THREAD

**Issue by smcardle** [RocketChat/Rocket.Chat.Apps-engine#203]
Hi

I am writing an App that does some checks on messages before they are sent by extending `IPreMessageSentExtend`. 
From the message I get the room `read.getRoomReader().getById(message.room.id)` and before proceeding I need to check the topic on the room....

This is my problem... There seems to be no way to get the `topic` set for the room. Is this an oversight in the API ??? as it's clearly a property of the room in the database.

Steve

**Comment by lolimay** [comment]
![image](https://user-images.githubusercontent.com/32427260/72220112-61272080-3588-11ea-91df-ee4b999cf016.png)

Sorry, I didn't see the `topic` field for a room. Where did you see it?

**Comment by lucassartor** [comment]
Hi Steve! 
Now the `topic` value of a `room` is called `description`.
That value was not mapped as a `IRoom` value, that's why you were unable to get it from a certain `room`.
I added a PR that resolves that, hope it resolves your issue!
