### ISSUE TITLE
[BUG] message.id in executePostMessageUpdated is missing

### ISSUE THREAD

**Issue by meomay503** [RocketChat/Rocket.Chat.Apps-engine#231]
I am implementing an auto-translation API call in executePostMessageUpdated but I found that the id in message object is missing.

Apps should be able to access the id field of messages via this hook.

Apps API version: 1.7.0
Rocket.Chat 2.2.0

**Comment by matheusbsilva137** [comment]
Hi, @meomay503!

We couldn't reproduce the reported bug in the latest version of our Apps Engine. Could you please tell me if you are still having problems with this issue or if it has already been fixed for you?

**Comment by meomay503** [comment]
Hi @matheusbsilva137, I have just taken a test on the latest version of Apps Engine. The bug seems to be fixed somehow. Thank you very much for your effort ^^. I will close this issue now
