### ISSUE TITLE
Save app user id instead of using its username

### ISSUE THREAD

**Issue by marceloschmidt** [RocketChat/Rocket.Chat.Apps-engine#243]
When the app creates a user, it should store its userId in its settings and refrain from using the bot's username `app.appname`. A bot's username is editable. A userId is not.

**Comment by lolimay** [comment]
Hi @marceloschmidt ! Not sure I followed but what does `store its userId in its settings` mean? Do you mean we cann't provide https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/e9ca98a44423510ae1e91b519e8014ba214ad515/src/definition/App.ts#L60 (getAppuserUsername) method because admins can change app user's username.

If so, yeah I agree. Perhaps, we need to move it under `read` to get its value dynamically. What do you think of it? @d-gubert

**Comment by marceloschmidt** [comment]
Yes exactly. You're forcing the app to use a username that is mutable. My opinion is that we should allow the apps to change that...

**Comment by AymanAzzam** [comment]
did you mean that UserID will never change after creation while the username is not, so we need to depend on the UserID in the code instead of the username ?

**Comment by marceloschmidt** [comment]
Yes, exactly.

**Comment by AymanAzzam** [comment]
I will try to solve it.

**Comment by lolimay** [comment]
Hi @AymanAzzam . Are you working on it? If you are working it then I can move the focus to other issues to make sure we don't do the duplicate work.

**Comment by AymanAzzam** [comment]
Hi @lolimay . I'm facing some problems in opening the project as I told you on Rocket.Chat. so when I solve them, I will work on this issue.

**Comment by lolimay** [comment]
> Hi @lolimay . I'm facing some problems in opening the project as I told you on Rocket.Chat. so when I solve them, I will work on this issue.

Great! What's your username on open.rocket.chat server?

**Comment by AymanAzzam** [comment]
> > Hi @lolimay . I'm facing some problems in opening the project as I told you on Rocket.Chat. so when I solve them, I will work on this issue.
> 
> Great! What's your username on open.rocket.chat server?

ayman.azzam16

**Comment by marceloschmidt** [comment]
@lolimay any update here?

**Comment by lolimay** [comment]
> @lolimay any update here?

Hi, @marceloschmidt . I have make a pr at https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/257 by deprecate `getAppUserUsername` method and introduce `read.getAppUser` method. @d-gubert should inlcude these commits on beta version later.

**Comment by d-gubert** [comment]
Closing as it has been solved on v1.14
