### ISSUE TITLE
Bring Textarea to IInputBlock UIKit Element

### ISSUE THREAD

**Issue by juzser** [RocketChat/Rocket.Chat.Apps-engine#262]
Can we bring more Element type into the IInputBlock, e.g: Textarea? :)

**Comment by d-gubert** [comment]
The multi line input is coming to the next version of the Apps-Engine! It has already been merged in our [Alpha branch](https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/281) and is expected to be released by the end of the month (along with Rocket.Chat v3.5)

**Comment by d-gubert** [comment]
Closing it as it is already available in the latest release
