### ISSUE TITLE
Add new Omnichannel event handlers

### ISSUE THREAD

**Issue by renatobecker** [RocketChat/Rocket.Chat.Apps-engine#270]
Guys, we need to be able to handle the following Omnichannel events through the `Apps-Engine`:

- `On Create / Upate Visitor`
- `OnSaveGuestInfo` -> [Here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/lib/Livechat.js#L280)
- `OnSaveRoomInfo` -> [Here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/lib/Livechat.js#L467)
- `OnTransferRoom`-> [Here](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/lib/Livechat.js#L580)

Also, we need to be able to request and send the chat transcript through the Apps-Engine:
- [Here is the method to set custom fields](https://github.com/RocketChat/Rocket.Chat/blob/develop/app/livechat/server/lib/Livechat.js#L400)

I'm bringing it up because we have planned to implement new Apps over the next quarter and those events/methods are essential to achieve this goal.

- Another missing feature: Set/Update `Visitor Custom Fields`;

**Comment by meomay503** [comment]
it is the same problem with #199

**Comment by d-gubert** [comment]
Event `onTransferRoom` has been added to version 1.17 - available now in Rocket.Chat 3.6.0
