### ISSUE TITLE
[Question] Is there a way to use setTimeout() or setInterval() in Rocket.Chat App?

### ISSUE THREAD

**Issue by murtaza98** [RocketChat/Rocket.Chat.Apps-engine#278]
I tried using `setInterval()` and `setTimeout()` in an Rocket.Chat App, but it didn't work. 

Most probably the issue is because `timers` module(a prebuilt node module) is not supported by Apps-Engine. If this is the issue, then is there a way to achieve similar functionality in an Rocket.Chat App, i.e trigger a function after a specific number of seconds?

**Comment by graywolf336** [comment]
There is not and it is by design. App accessors are only guaranteed for the lifetime of an event. Which using those timers would lift other code out of the lifecycle of an event and potentially cause other issues. That is what #89 was originally meant to fix, but priorities have shifted since then.
