### ISSUE TITLE
Add http.patch function

### ISSUE THREAD

**Issue by joaopedropannain** [RocketChat/Rocket.Chat.Apps-engine#286]
Hi,

I would like to create the patch method on HTTP service.

I changed my local function, but want to sent to you.

Best Regards.

**Comment by graywolf336** [comment]
Feel free to submit a pull request :)

**Comment by joaopedropannain** [comment]
I made it, but need required permission.

**Comment by joaopedropannain** [comment]
Is there a way to change or add this function on run time http method?

**Comment by d-gubert** [comment]
Hey @joaopedropannain ! Did you fork our repo into your own? That way you can push your changes to your fork and then submit a PR from there to our repo :)

**Comment by d-gubert** [comment]
Feature has been added :)
