### ISSUE TITLE
Error when a file is uploaded by a Livechat visitor

### ISSUE THREAD

**Issue by renatobecker** [RocketChat/Rocket.Chat.Apps-engine#292]
When a livechat end-user(visitor) uploads a file the following error is raised:

<img width="571" alt="Screen Shot 2020-08-01 at 20 23 12" src="https://user-images.githubusercontent.com/59577424/89112123-d713ac00-d434-11ea-9f6b-4031205d0b5d.png">

I took a look at the code and I guess I found the reason for the error:
https://github.com/RocketChat/Rocket.Chat/blob/develop/app/apps/server/converters/uploads.js#L56

Instead of:
`const result = this.orch.getConverters().get('users').convertByToken(upload.visitorToken);`

it should be:
`const result = this.orch.getConverters().get('visitor').convertByToken(upload.visitorToken);`

**Comment by d-gubert** [comment]
Can you confirm that applying this change solves your problem?

**Comment by renatobecker** [comment]
> Can you confirm that applying this change solves your problem?

Yeah, we applied the suggested changes locally and everything worked fine.

**Comment by d-gubert** [comment]
Right, so would you like us to open the PR with those changes? Or would you rather do it, since you already have it applied?

**Comment by renatobecker** [comment]
> Right, so would you like us to open the PR with those changes? Or would you rather do it, since you already have it applied?

I can handle it, no worries.
Thanks.

**Comment by renatobecker** [comment]
Closing in favor of: https://github.com/RocketChat/Rocket.Chat/pull/18474
