### ISSUE TITLE
Scan the code for what the Rocketlet provides

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-engine#3]
> One of the major USPs of Rocket.Chat compared to others is it's availability on premise with enterprise features for companies. I'd not install a single Rocketlet if I was unsure what it can do.

**Comment by timkinnane** [comment]
Copy pasta from #2 because it seems to relate more here:

> Maybe a permissions layer (which could be quite simple for now) should be considered for this type of thing, to keep instance owners informed of security risks when installing Rocketlets, then we don't have to be overly protective and limiting. Similar to permissions for users, but implemented like adding a facebook app, e.g.
> 
> This Rockelet can
> 
> modify user roles
> modify messages
> The above could have some correlation to the internal API endpoints used in the Rocketlet source.

**Comment by d-gubert** [comment]
Closing this issue as it doesn't reflect the current state of the project anymore.

We are currently planning how the permission system will work and should be starting development in the next weeks.
