### ISSUE TITLE
Implement the Permissions

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-engine#30]
Ability to create, get, and check permissions.

This would be amazing for commands that only need to be given to certain people.

**Comment by piotrkochan** [comment]
It would be excellent to be able to give application permissions like "get user data" (profile? groups/channels he belongs to?) or "get available groups" and other similar.

**Comment by d-gubert** [comment]
This should be a responsibility of the app itself - to control whoever can interact with it, and provide a means to configure such "access list".

@piotrkochan your suggestion is more towards an "app permission system" (similar to mobile apps), right? This is on our roadmap for the short-term now.

We will provide a docs article discussing how to implement access control in apps in the future.
