### ISSUE TITLE
Add support for User typing indicator

### ISSUE THREAD

**Issue by renatobecker** [RocketChat/Rocket.Chat.Apps-engine#303]
In order to provide a better UX, we need to support `user typing indicator` through the Apps-Engine.
We have been implementing integrations with `chatbot platforms` as well as other `external applications` and the ability to display that a user is typing is missing. 
For instance,  the`Salesforce Live Agent` API provides an endpoint to listen to users who are typing on `Salesforce platform`, so it would be nice to listen to that API and to upstream the event/data in the room where the external user is chatting.

That's, also, a very nice feature for omnichannel rooms that are served by chatbot agents, for instance, `Dialogflow chatbots`.

**Comment by d-gubert** [comment]
![image](https://user-images.githubusercontent.com/1810309/92753007-d50c0980-f35f-11ea-9086-1949cbaba1ea.png)

Just clarifying, is this the use case you've mentioned?

**Comment by renatobecker** [comment]
> ![image](https://user-images.githubusercontent.com/1810309/92753007-d50c0980-f35f-11ea-9086-1949cbaba1ea.png)
> 
> Just clarifying, is this the use case you've mentioned?

Yeah @d-gubert you definitely got it.
