### ISSUE TITLE
Implement oEmbed Url Previews Handler

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-engine#31]
# Idea
A Rocketlet can register a url it would like to add additional information to the request of the oEmbed information request.

# Example
Rocketlet which allows for a GitHub authentication information to be attached to oEmbed requests out to GitHub, this way links to private repositories can have their information shown instead of showing nothing.

**Comment by d-gubert** [comment]
Apps can currently intercept the URLs from messages, do their own request, and modify the original message to include either `attachments` or UIKit blocks to enrich the content.

The Engine shouldn't need to provide any other special functionality for this to be possible

**Comment by porg** [comment]
@d-gubert Could you please provide link(s) to relevant documentation how to set this up?
- Note: I found nothing myself at https://docs.rocket.chat

## How does Rocket Chat's Link Preview work?
And in what aspects can a RC admin or user one influence its behavior?

1) **Server-side**: RC Server (consumer) via an embed mechanism (oEmbed, OpenGraph, etc) gets the data from the provider (e.g. Jira or Github) and integrates that into the markup of the message.
    - Then you could set up one API-key or pseudo-user per each external website requiring login and this one fetches everything needed for the Link Preview, stores the assets in copy on the server, and embeds the markup into the message.

2) **Cient-side**: The message contains the URL as-is, and then the client fetches it?
    - Then each user would need to set up his credentials per service for link preview fetching.
