### ISSUE TITLE
How to prevent a user sigin

### ISSUE THREAD

**Issue by codeneno** [RocketChat/Rocket.Chat.Apps-engine#322]
sir ,How to prevent a user sigin,we wan't to define a role to present some user sigin our site

**Comment by meomay503** [comment]
add app role for that user may help

**Comment by graywolf336** [comment]
> How to prevent a user sigin
Not possible with the Apps Engine presently as you can not update the `isEnabled` property of users.
https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/b358174ee83a122f063e80362e866b5c15942d59/src/definition/users/IUser.ts#L10
