### ISSUE TITLE
New created apps cannot be deployed successfully if using default config

### ISSUE THREAD

**Issue by lolimay** [RocketChat/Rocket.Chat.Apps-engine#345]
Just to be here FYI: The new `@types/node` package does not support Typescript 2 anymore (https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47248#issuecomment-686940047). If you guys meet some issues while packaging/deploying the app to the server recenctly. Please change your `@type/node`'s version to `13.11.0` (or lower) instead of `^13.11.0` or change your `typescript`'s version to the lastest one in your `package.json`. The run the command `npm i` again to fix the issue.

![](https://raw.githubusercontent.com/lolimay/images/main/1605014464408.png)

**Comment by d-gubert** [comment]
We've updated the default versions in the templates, can you check if this still happen?

**Comment by lolimay** [comment]
This issue was fixed in `@rocket.chat/apps-cli/1.7.3`.
