### ISSUE TITLE
[Question] Recurring Schedule interval param

### ISSUE THREAD

**Issue by juzser** [RocketChat/Rocket.Chat.Apps-engine#347]
Hi guys, 

Thank you for bring schedule feature into app-engine. I've waited for it for a long time (I had to use hubot instead). 
I have a plan to build a schedule app, and see everything are all good now. 

But I have some questions about the `interval` param in `IRecurringSchedule`:
1. It can be a "cron string", do you mean it's the same as: crontab.guru?
2. The human-interval as I known, it does not support any recurring string? 
3. The `interval` number type is milliseconds or seconds? 

And side question: can you give me a quick explanation about `IRecurringStartup` please? 

Thank guys.

**Comment by meomay503** [comment]
as I see they are using [Agenda](https://github.com/Agenda/agenda#readme) which supports cron string 🤔

**Comment by juzser** [comment]
Thank, I know that. 
But you cannot use *Agenda* if you want to schedule a task with specific date. 
Never mind, I found the pattern, they're using normal cron pattern, that can be generate via crontab.guru. 
For example: The pattern to executing the task on Monday at 9:00 is `0 9 * * 1`. 

Anyway, here is the "more details" doc for Schedule API: 
https://github.com/RocketChat/docs/blob/9a086611ea610d1760870e838d92b4b9e5000496/apps-development/scheduler-api.md
