### ISSUE TITLE
Implement the IterableIterators

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-engine#37]
Ref: https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/pull/45

**Comment by thassiov** [comment]
The issue is outdated because it does not reflect the current state of the engine

**Comment by graywolf336** [comment]
This actually does and is more a guidance than a specific thing. Whenever there is more than one item, it would be better to implement the IterableIterator or AsyncIterableIterator.
