### ISSUE TITLE
Fix typo: getNotifer -> getNotifier

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.Apps-engine#42]
https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/master/src/server/accessors/Modify.ts#L40

**Comment by graywolf336** [comment]
@rodrigok can we slip this into the v1 release as well? :see_no_evil: me and my terrible spelling

**Comment by rodrigok** [comment]
@graywolf336 sure

**Comment by graywolf336** [comment]
Thanks :) @rodrigok

**Comment by timkinnane** [comment]
@graywolf336 -->> https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md 👍

**Comment by graywolf336** [comment]
@timkinnane too awesome, thanks for sharing! 😂
