### ISSUE TITLE
[BUG] Unable to start RocketChat under windows

### ISSUE THREAD

**Issue by twi123** [RocketChat/Rocket.Chat.Apps-engine#46]
Unable to run RocketChat under Windows due exception:
```
...
 Exception in callback of async function: Error: Could not find the Apps TypeScript Definition Package Version!
...
```
because of [AppPackageParser.ts@151](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/7bf4cc158f66c1a99d60ec5b1a7ee704e3c75176/src/server/compiler/AppPackageParser.ts#L151)
```
...
        const prodLocation = __dirname.split('@rocket.chat/apps-engine')[0] + '@rocket.chat/apps-ts-definition/package.json';
...
```

Splitting path by substring contains **/** - bad idea.

**Comment by thassiov** [comment]
Closing issue as user already states that the problem is fixed
https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/47#issuecomment-425118948
