### ISSUE TITLE
Allow an App to register a "user/bot"

### ISSUE THREAD

**Issue by rodrigok** [RocketChat/Rocket.Chat.Apps-engine#49]
@graywolf336 commented on [Thu Jan 11 2018](https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/25)

Allow the Rocket.Chat Apps to register a user, aka a bot, that will then populate the auto-completes when you go to tag a user. This will allow applications to "impersonate" a user and "converse" with them.

---

@mrsimpson commented on [Thu Jan 11 2018](https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/25#issuecomment-357068567)

I believe that this property (reading messages and impersonating a response) could turn RocketChat into a bot platform and give a spin at the Rocket.Chat Apps even with the limited (text-only) scope. Feature-wise, it’s not much more compared to a slash-command (a textual interface), but it would allow bot developers to even capture a conversational state inside or outside of Rocket.Chat

---

@timkinnane commented on [Thu Jan 11 2018](https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/25#issuecomment-357105272)

@mrsimpson Most of what you're talking about is how the platform already works to support Hubot for instance. Via the [hubot-rocketchat](https://github.com/RocketChat/hubot-rocketchat) adapter, which uses [Asteroid](https://github.com/RocketChat/asteroid) to log in and set up channel subscriptions and send/receive.

@graywolf336  +1 on this. But I'll also flag that it ties into something I'd like to do for general bot support and testing. I think the creation process could be streamlined for bots, such as [core issue 3818](https://github.com/RocketChat/Rocket.Chat/issues/3818) and other mods to register bots programatically more simply than users.

For both bot and app testing, I'm thinking about a feature that would support creation of temporary users in private channels. So that neither the channel or users are visible to the community and they can be easily wiped away. I know this is overloading this particular ticket, just giving some context before anyone jumps to a solution.

---

@mrsimpson commented on [Wed Jan 17 2018](https://github.com/RocketChat/Rocket.Chat.Apps-ts-definition/issues/25#issuecomment-358269494)

@graywolf336 funny enough, guggy itself has pictured it like that
http://s3.amazonaws.com/guggyresources/guggyexample.gif

**Comment by d-gubert** [comment]
@rodrigok Do you think the current flow of giving apps an "app user" when they're installed solves this discussion here?

Do you think this is still interesting for the project?

**Comment by rodrigok** [comment]
I don't think so
