### ISSUE TITLE
Handle Rocketlets which error out during compile time

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Apps-engine#7]
Currently Rocketlets which error out during compile time, for any numerous reasons, are ignored and not added anywhere that they can successfully be removed or updated and doing so with their `id` will actually error out. So, special provisions need to be made for Rocketlets which error out during compile time and enable time.

**Comment by d-gubert** [comment]
The current behavior when an App has a compilation error is to flag it as failed on the Administration screen - thus this seems to have been solved.

If you think this is still a problem, feel free to reopen.
