### ISSUE TITLE
Engine Logger doesn't log from inside slash command executions

### ISSUE THREAD

**Issue by d-gubert** [RocketChat/Rocket.Chat.Apps-engine#86]
Calling `this.app.getLogger().log()` (or any of the logger's methods) inside a slash command class doesn't save a log in the app's "View logs" in Rocket.Chat

**Comment by graywolf336** [comment]
You sure? As it does for me..
<img width="660" alt="screen shot 2018-10-31 at 11 48 43 am" src="https://user-images.githubusercontent.com/850391/47815813-656a7380-dd1f-11e8-82b7-03b79fbe4310.png">

**Comment by d-gubert** [comment]
I'm going to test further, but I wasn't able to see it there. If I'm able to reproduce it, I'll share the slash command class code, as it could probably be something wrong in there :)

**Comment by d-gubert** [comment]
I still had the problem, but was solved by this https://github.com/RocketChat/Rocket.Chat.Apps-engine/pull/95
